[project]
name = "mastermind"
version = "0.1.0"
description = "Mastermind game application"
authors = [
  { name="Noemie Dubouloz", email="noemie.dubouloz@insa-strasbourg.fr" },
  { name="Perrine Rousset", email="perrine.rousset@insa-strasbourg.fr" },
  { name="Victoria Blanchard", email="victoria.blanchard@insa-strasbourg.fr" }
]
readme = "README.md"
requires-python = ">=3.10"
license = { text = "BSD-3-Clause" }
classifiers = ["Programming Language :: Python :: 3"]

dependencies = []

[project.optional-dependencies]
test = ["pytest"]
dev = ["ruff","pylint"]

[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["mvc", "mvc.model"]

[tool.pytest.ini_options]
pythonpath = [".", "mvc"]

[tool.ruff]
# Longueur de ligne standard (comme Black)
line-length = 88
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "I", "N"]
fixable = ["ALL"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"