name: Lint, test and build mastermind project

on: [push]   # a remettre quand ca marchera 

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: get code
      uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3 
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        python -m pip install --upgrade pip
        pip install -e .
        pip install -r requirements.txt
    
    - name: Install build
      run: |
        source .venv/bin/activate
        python -m pip install build
        python -m build --wheel

    - name: Analysing the code with pylint
      run: |
        source .venv/bin/activate
        pylint $(git ls-files '*.py') 

  test:
    runs-on: ubuntu-latest
    steps:
    - name: get code
      uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3 
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        python -m pip install --upgrade pip
        pip install -e .
        pip install -r requirements.txt
    - name: Analysing the code with pytest
      run: |
        source .venv/bin/activate
        pytest

  build:
    runs-on: ubuntu-latest
    steps:
    - name: get code
      uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3 
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        python -m pip install --upgrade pip
        pip install -e .
        pip install -r requirements.txt
    - name: Install build 
      run: |
        source .venv/bin/activate
        python -m pip install build
        python -m build --wheel
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with: 
        name: executable
        path: dist/*  #a changer quand on aura le bon path 
        
  